return {}

-- return {
--     'olimorris/codecompanion.nvim',
--     dependencies = {
--         'nvim-lua/plenary.nvim',
--         'nvim-treesitter/nvim-treesitter',
--         -- 'hrsh7th/nvim-cmp',              -- Optional: For using slash commands and variables in the chat buffer
--         -- 'nvim-telescope/telescope.nvim', -- Optional: For using slash commands
--         -- { 'MeanderingProgrammer/render-markdown.nvim', ft = { 'markdown', 'codecompanion' } }, -- Optional: For prettier markdown rendering
--         -- { 'stevearc/dressing.nvim', opts = {} }, -- Optional: Improves `vim.ui.select`
--     },
--     config = function()
--         require('codecompanion').setup({
--             strategies = {
--                 chat = {
--                     adapter = 'tabby',
--                     keymaps = {
--                         send = {
--                             modes = { n = "<C-s>", i = "<C-s>" },
--                         },
--                         close = {
--                             modes = { n = "<C-c>", i = "<C-c>" },
--                         },
--                     },
--                 },
--                 -- inline = { adapter = 'tabby' },
--             },
--             adapters = {
--                 tabby = function()
--                     return require('codecompanion.adapters').extend('openai_compatible', {
--                         env = {
--                             url = 'http://localhost:8080',
--                             api_key = 'auth_e9ed8b0c3e1e4824969c2a4b24b9fd3b',
--                             chat_url = '/v1/chat/completions',
--                         },
--                         schema = {
--                             model = {
--                                 default = 'Qwen2-1.5B-Instruct',
--                                 choices = { 'Qwen2-1.5B-Instruct' },
--                             },
--                         },
--                     })
--                 end,
--                 -- ollama = function()
--                 --     return require('codecompanion.adapters').extend('ollama', {
--                 --         env = {
--                 --             url = 'https://localhost',
--                 --             api_key = 'OLLAMA_API_KEY',
--                 --         },
--                 --         headers = {
--                 --             ['Content-Type'] = 'application/json',
--                 --             ['Authorization'] = 'Bearer ${api_key}',
--                 --         },
--                 --         parameters = {
--                 --             sync = true,
--                 --         },
--                 --     })
--                 -- end,
--             },
--             -- keys = {
--             --     {
--             --         '<leader>nr',
--             --         ':CodeCompanion<CR>',
--             --         desc = 'Quick change',
--             --         mode = { 'n', 'v' },
--             --     },
--             --     {
--             --         '<leader>no',
--             --         ':CodeCompanionChat tabby<CR>',
--             --         desc = 'Open AI chat',
--             --         mode = { 'n', 'v' },
--             --     },
--             -- },
--         })
--
--         vim.keymap.set('n', 'cr', ':CodeCompanion<CR>', {
--             noremap = true,
--             silent = true,
--             desc = 'Code Companion',
--         });
--
--         vim.keymap.set('n', 'cc', ':CodeCompanionChat tabby<CR>', {
--             noremap = true,
--             silent = true,
--             desc = 'Code Companion Chat',
--         });
--     end
-- }
