#!/bin/bash

# Assumes .dotfiles is in ~

# BASH
ln -sb ~/.dotfiles/.bashrc ~/.bashrc
ln -sb ~/.dotfiles/.profile ~/.profile
ln -sb ~/.dotfiles/.bashTweaks ~/.bashTweaks
ln -sb ~/.dotfiles/.bash_logout ~/.bash_logout

# GIT & scm_breeze
ln -sb ~/.dotfiles/.gitglobal ~/.gitconfig

ln -sb ~/.dotfiles/.git.scmbrc ~/.git.scmbrc
ln -sb ~/.dotfiles/.scmbrc ~/.scmbrc
ln -sb ~/.dotfiles/.scm_breeze ~/.scm_breeze

# BYOBU
ln -sb ~/.dotfiles/.byobu .byobu
ln -sb ~/.dotfiles/.screenrc .screenrc

# VIM
ln -sb ~/.dotfiles/.vim .vim
ln -sb ~/.dotfiles/.vim/vimrc .vimrc

# Other
ln -sb ~/.dotfiles/.htoprc ~/.htoprc
