#!/bin/bash

# Assumes .dotfiles is in ~

# BASH
ln -sb ~/.dotfiles/.bashrc ~/.bashrc
ln -sb ~/.dotfiles/.profile ~/.profile
ln -sb ~/.dotfiles/.bashTweaks ~/.bashTweaks

# FISH
ln -si ~/.dotfiles/config.fish ~/.config/fish/config.fish

# GIT
ln -sb ~/.dotfiles/.gitconfig ~/.gitconfig

# TMUX
ln -si ~/.dotfiles/.tmux.conf ~/.tmux.conf

# VIM
ln -si ~/.dotfiles/nvim ~/.config/nvim

# Other
ln -sb ~/.dotfiles/.htoprc ~/.htoprc
