# Tomorrow Night scheme by Chris Kempson (http://chriskempson.com)
# Colors yanked from from base16-vim/base16-tomorrow-night.vim
# Based on base16_default_dark by RayGervais <raygervais@hotmail.ca>

# // Grayscale
# @black:           #1d1f21; // 00
# @very-dark-gray:  #282a2e; // 01
# @dark-gray:       #373b41; // 02
# @gray:            #969896; // 03
# @light-gray:      #b4b7b4; // 04
# @very-light-gray: #c5c8c6; // 05
# @almost-white:    #e0e0e0; // 06
# @white:           #ffffff; // 07

# // Colors
# @red:             #cc6666; // 08
# @orange:          #de935f; // 09
# @yellow:          #f0c674; // 0A
# @green:           #b5bd68; // 0B
# @cyan:            #8abeb7; // 0C
# @blue:            #81a2be; // 0D
# @purple:          #b294bb; // 0E
# @brown:           #a3685a; // 0F

"ui.background" = { bg = "base00" }
"ui.virtual.whitespace" = "base02"
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.selection" = { bg = "base02" }
"ui.statusline" = { fg = "base04", bg = "base02" }
"ui.statusline.inactive" = { fg = "base03", bg = "base01" }
"ui.statusline.normal" = { fg = "base02", bg = "base0D" }
"ui.statusline.insert" = { fg = "base02", bg = "base0B" }
"ui.statusline.select" = { fg = "base02", bg = "base0E" }
"ui.help" = { fg = "base06", bg = "base01" }
"ui.text" = "base05"
"ui.text.focus" = "base05"
"ui.text.inactive" = { fg = "base04" }
"ui.linenr" = { fg = "base03", bg = "base01" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.bufferline.active" = { fg = "base06", bg = "base01" }

"attribute" = "base09"
"type" = "base0E"
"constructor" = "base05"
"constant" = "base09"
"constant.numeric" = "base09"
"constant.character.escape" = "base0C"
"string"  = "base0B"
"comment" = { fg = "base03", modifiers = ["italic"] }
"variable" = "base05"
"variable.builtin" = "base0E"
"variable.parameter" = "base0D"
"variable.other.member" = "base08"
"label" = "base0E"
"punctuation" = "base05"
"keyword" = "base0E"
"function" = "base0D"
"tag" = "base08"
"namespace" = "base0E"
"special" = "base0D"
"operator" = "base05"

"markup.heading" = "base0D"
"markup.list" = "base08"
"markup.bold" = { fg = "base0D", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"

"diff.plus" = "base0B"
"diff.delta" = "base09"
"diff.minus" = "base08"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "base01" }
"info" = "base0D"
"hint" = "base03"
"debug" = "base03"
"warning" = "base09"
"error" = "base08"

[palette]
base00 = "#1d1f21" # Default Background
base01 = "#282a2e" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#373b41" # Selection Background
base03 = "#969896" # Comments, Invisibles, Line Highlighting
base04 = "#b4b7b4" # Dark Foreground (Used for status bars)
base05 = "#c5c8c6" # Default Foreground, Caret, Delimiters, Operators
base06 = "#e0e0e0" # Light Foreground (Not often used)
base07 = "#ffffff" # Light Background (Not often used)
base08 = "#cc6666" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#de935f" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#f0c674" # Classes, Markup Bold, Search Text Background
base0B = "#b5bd68" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#8abeb7" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#81a2be" # Functions, Methods, Attribute IDs, Headings
base0E = "#b294bb" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#a3685a" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
