-- require('lint').linters_by_ft = {
--     javascript = {'eslint',},
--     typescript = {'eslint',},
-- }
--
-- vim.api.nvim_create_autocmd({ "BufEnter", "BufWritePost" }, {
--   callback = function()
--     require("lint").try_lint()
--   end,
-- })
