local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>/', builtin.find_files, {})
vim.keymap.set('n', '<leader>a', builtin.git_files, {})
vim.keymap.set('n', '<leader>s', function()
    builtin.grep_string({ search = vim.fn.input("Grep Files > ") })
end)
vim.keymap.set('n', '<leader>h', builtin.help_tags, {})
