local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>/', ':lua require"telescope.builtin".find_files({ hidden = true, no_ignore = true })<CR>', {})
vim.keymap.set('n', '<leader>a', builtin.git_files, {})
vim.keymap.set('n', '<leader>b', builtin.buffers, {})
vim.keymap.set('n', '<leader>f', builtin.live_grep, {})
vim.keymap.set('n', '<leader>h', builtin.help_tags, {})
